// <auto-generated />
using System;
using KitProjects.MasterChef.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KitProjects.MasterChef.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210328185110_RecipeAndManyToManyRelationships")]
    partial class RecipeAndManyToManyRelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbCategoryDbIngredient", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("DbCategoryDbIngredient");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DbRecipe");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeCategory", b =>
                {
                    b.Property<Guid>("DbRecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DbCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DbRecipeId", "DbCategoryId");

                    b.HasIndex("DbCategoryId");

                    b.ToTable("DbRecipeCategory");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeIngredient", b =>
                {
                    b.Property<Guid>("DbRecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DbIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IngredientMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IngredientxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DbRecipeId", "DbIngredientId");

                    b.HasIndex("DbIngredientId");

                    b.ToTable("DbRecipeIngredient");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DbRecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DbRecipeId");

                    b.ToTable("DbRecipeStep");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeStepIngredient", b =>
                {
                    b.Property<Guid>("DbIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DbRecipeStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DbIngredientId", "DbRecipeStepId");

                    b.HasIndex("DbRecipeStepId");

                    b.ToTable("DbRecipeStepIngredient");
                });

            modelBuilder.Entity("DbCategoryDbIngredient", b =>
                {
                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbIngredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeCategory", b =>
                {
                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbCategory", "DbCategory")
                        .WithMany("RecipesCategoriesLink")
                        .HasForeignKey("DbCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbRecipe", "DbRecipe")
                        .WithMany("RecipeCategoriesLink")
                        .HasForeignKey("DbRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbCategory");

                    b.Navigation("DbRecipe");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeIngredient", b =>
                {
                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbIngredient", "DbIngredient")
                        .WithMany("RecipeIngredientsLink")
                        .HasForeignKey("DbIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbRecipe", "DbRecipe")
                        .WithMany("RecipeIngredientLink")
                        .HasForeignKey("DbRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbIngredient");

                    b.Navigation("DbRecipe");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeStep", b =>
                {
                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbRecipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("DbRecipeId");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeStepIngredient", b =>
                {
                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbIngredient", "DbIngredient")
                        .WithMany("StepIngredientsLink")
                        .HasForeignKey("DbIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitProjects.MasterChef.Dal.Database.Models.DbRecipeStep", "DbRecipeStep")
                        .WithMany("StepIngredientsLink")
                        .HasForeignKey("DbRecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbIngredient");

                    b.Navigation("DbRecipeStep");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbCategory", b =>
                {
                    b.Navigation("RecipesCategoriesLink");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbIngredient", b =>
                {
                    b.Navigation("RecipeIngredientsLink");

                    b.Navigation("StepIngredientsLink");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipe", b =>
                {
                    b.Navigation("RecipeCategoriesLink");

                    b.Navigation("RecipeIngredientLink");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("KitProjects.MasterChef.Dal.Database.Models.DbRecipeStep", b =>
                {
                    b.Navigation("StepIngredientsLink");
                });
#pragma warning restore 612, 618
        }
    }
}
